source "https://rubygems.org"
ruby "3.4.2"

gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "pg", "~> 1.5"
gem "pgvector", "~> 0.3"
gem "sidekiq", "~> 7.3"
gem "sidekiq-unique-jobs"
gem "bootsnap", require: false
gem "rack-cors"
gem "image_processing", "~> 1.12"
gem "mini_magick"
gem "rtesseract"
gem "annotaterb", require: false
gem "active_storage_validations"
gem "jbuilder"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "dotenv-rails"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
end
