source "https://rubygems.org"
ruby "3.4.2"

gem "rails", "~> 8.0.1"
gem "pg", "~> 1.5"
gem "pgvector", "~> 0.3"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "thruster", require: false

gem "devise"
gem "devise-jwt"
gem "cancancan"
gem "jbuilder"
gem "sidekiq"
gem "rack-cors"
gem "dotenv-rails", groups: [:development, :test]
gem "annotaterb"
gem "interactor"
gem "ostruct"
gem "active_storage_validations"
gem "image_processing", "~> 1.12"
gem "activestorage"
gem "rtesseract"
gem "mini_magick"
gem "pdf-reader"
gem 'ruby-openai'
gem "tzinfo-data", platforms: %i[windows jruby]
gem "karafka", "~> 2.5"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "shoulda-matchers"
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.1'
  gem 'simplecov', require: false
end